HTTP/1.0 503 Service Unavailable
Cache-Control: no-cache
Connection: close
Content-Type: text/html

<html><body><h1>503 Ningun Servidor Esta Disponible para atender su solicitud</h1>
Revise su conexion.
</body></html>